server:
  port: 8888

logging:
  path: logs
  file: logs/mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.190:3306/course?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
